/*
 * File: app/controller/MainPanelController.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('EmailPrototype.controller.MainPanelController', {
    extend: 'EmailPrototype.controller.AbstractFdController',
 
    models: [],
    views: ['MainPanel'],
    requires: [],

        config:{
  //        navigationPanelController: null,
          eastItemController: null,
          centerItemController: null
        },

       init: function(application) {
          var me = this;

 //       navigationPanelController = me.createController('west.NavigationPanelController');
        eastItemController = me.createController('east.InfoPanelController');
        centerItemController = me.createController('center.ContentPanelController');
    	},

    	getViewItems: function(){
    		var me = this, eastItem, contentItem,items = new Array();
        // var westItem;
      //  debugger; //MAINNNN 
    		// westItem = navigationPanelController.getViewConfig();
	     // westItem = Ext.apply(westItem, {collapsible: true,region: 'west'});
	     // items.push(westItem);

        eastItem = eastItemController.getViewConfig();
        eastItem = Ext.apply(eastItem, {collapsible: true,region: 'east'});
        items.push(eastItem);

        contentItem = centerItemController.getViewConfig();
        contentItem = Ext.apply(contentItem, {flex: 1, region: 'center'});
        items.push(contentItem);

          return items;
    	},


    	getViewConfig:function(){
	        var me = this,containedItems, westItem, cfg;

	        var viewId = me.getViewId('mainpanel');
	      	containedItems = me.getViewItems();

	        cfg = {
	            xtype: 'mainpanel',
	            itemId: viewId,
	            items: containedItems
	            
	        }

     //     debugger;
	        return cfg;
    	}

});
