/*
 * File: app/controller/ToolbarController.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('EmailPrototype.controller.ToolbarController', {
    extend: 'EmailPrototype.controller.AbstractFdController',

    init: function(application) {
        var me = this;
        this.control({
            "#NewButton": {
                click: this.onNewButtonClick
            }
        });
    },

    getViewConfig:function(){
        var me = this;
        var viewId = me.getViewId('toptoolbar');
        cfg = {
            xtype: 'toptoolbar',
            itemId: viewId
        }
        return cfg;
    },

    onNewButtonClick: function(button, e, eOpts) {
        var contentPanel = button.up('#contentpanelCenter');
        //debugger;
        if(contentPanel.getComponent(0).getXType() === 'mailgrid') {
           // console.log('mailgrid');
            Ext.create('EmailPrototype.view.NewMessageWindow');
        } else {
          //  console.log('todogrid');
            Ext.create('EmailPrototype.view.NewTodoWindow');
        }

    },

    

});
