/*
 * File: app/controller/ViewportController.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('EmailPrototype.controller.ViewportController', {
    extend: 'EmailPrototype.controller.AbstractFdController',

    init: function(application){
         var me = this,
            toolbarController, mainController;

       
        // Create 1 instances of the MainPanelController controller. 
        // Ids of controllers are saved in me.dynamicControllers
        mainController = me.createController('MainPanelController');
        toolbarController = me.createController('ToolbarController');
     },

    getViewItems: function(){
        var me = this,
            mainView, toolbar,
            items = new Array();
    
       toolbar = toolbarController.getViewConfig();
       items.push(toolbar);
       
       mainView = mainController.getViewConfig();
       items.push(mainView);
    
        return items;
    },

    getViewConfig:function(){
        var me = this, containedItems;

        var viewId = me.getViewId('maincard');
        containedItems = me.getViewItems();
        
        cfg = {
            xtype: 'panel',
            anchor: '100% -46',
            itemId: viewId,
            header: false,
            layout: {
                type: 'card',
                deferredRender: false
            },
            items: containedItems
        }
        return cfg;
    },

    

    

});
