/*
 * File: app/model/MailFolder.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('EmailPrototype.model.MailFolder', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field',
        'Ext.data.association.HasMany'
    ],
    uses: [
        'EmailPrototype.model.MailMessage'
    ],

    fields: [
        {
            name: 'folder'
        },
        {
            name: 'children'
        }
    ],

    hasMany: [
        {
            associationKey: 'messages',
            model: 'EmailPrototype.model.MailMessage',
            name: 'messages'
        },
        {
            associationKey: 'children',
            model: 'EmailPrototype.model.MailFolder',
            name: 'children'
        }
    ]
});