/*
 * File: app/view/TodoGrid.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('EmailPrototype.view.center.TodoGrid', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.todogrid',


    title: 'Todo List',
    forceFit: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'maingridtoolbar',
                    dock: 'top'
                }
            ],
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'title',
                    text: 'Title',
                    flex: 1
                },
                {
                    xtype: 'booleancolumn',
                    dataIndex: 'complete',
                    text: 'Complete',
                    flex: 0.3
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'duedate',
                    text: 'Duedate',
                    flex: 0.6
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'notes',
                    text: 'Notes',
                    flex: 2
                }
            ]
        });

        me.callParent(arguments);
    }

});