/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('EmailPrototype.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'EmailPrototype.view.MailPanel',
        'EmailPrototype.view.InformationPanel',
        'EmailPrototype.view.ContentPanel',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.Text',
        'Ext.toolbar.Spacer',
        'Ext.form.Label',
        'Ext.button.Split',
        'Ext.menu.Menu',
        'Ext.menu.Item'
    ],

    layout: 'anchor',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'toolbar',
                    anchor: '100%',
                    height: 46,
                    items: [
                        {
                            xtype: 'textfield',
                            itemId: 'searchTextField',
                            hideLabel: true,
                            emptyText: 'Search'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnSearch',
                            text: 'Go'
                        },
                        {
                            xtype: 'button',
                            icon: 'images/searchPlus.png'
                        },
                        {
                            xtype: 'tbspacer',
                            flex: 1
                        },
                        {
                            xtype: 'label',
                            text: 'Someone'
                        },
                        {
                            xtype: 'button',
                            itemId: 'UserProfileButton',
                            icon: 'images/user.png'
                        },
                        {
                            xtype: 'button',
                            itemId: 'ExitButton',
                            icon: 'images/exit.png'
                        },
                        {
                            xtype: 'splitbutton',
                            icon: 'images/home.png',
                            menu: {
                                xtype: 'menu',
                                width: 120,
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    }
                                ]
                            }
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    anchor: '100% -46',
                    itemId: 'CardPanel',
                    header: false,
                    layout: {
                        type: 'card',
                        deferredRender: false
                    },
                    items: [
                        {
                            xtype: 'panel',
                            itemId: 'MainPanel',
                            defaults: {
                                margin: '5 5 5 5'
                            },
                            layout: 'border',
                            header: false,
                            items: [
                                {
                                    xtype: 'mailpanel',
                                    collapsible: true,
                                    region: 'west'
                                },
                                {
                                    xtype: 'informationpanel',
                                    collapseFirst: false,
                                    collapsible: true,
                                    region: 'east'
                                },
                                {
                                    xtype: 'contentpanel',
                                    flex: 1,
                                    region: 'center'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});