/*
 * File: app/store/TodoStore.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('EmailPrototype.store.TodoStore', {
    extend: 'Ext.data.Store',

    requires: [
        'EmailPrototype.model.Todo',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'EmailPrototype.model.Todo',
            storeId: 'TodoStore',
            proxy: {
                type: 'ajax',
                url: 'data/todo2.json',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});