/*
 * File: app/view/ContentPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('EmailPrototype.view.ContentPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.contentpanel',

    requires: [
        'EmailPrototype.view.MailGrid',
        'Ext.grid.Panel',
        'Ext.form.field.TextArea'
    ],

    height: 250,
    width: 400,
    layout: 'border',
    header: false,
    title: '',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            defaults: {
                margin: '5 5 5 5'
            },
            items: [
                {
                    xtype: 'container',
                    region: 'center',
                    itemId: 'contentpanelCenter',
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'mailgrid'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'south',
                    height: 150,
                    itemId: 'previewpanel',
                    layout: 'fit',
                    collapsible: true,
                    title: 'Preview',
                    items: [
                        {
                            xtype: 'textareafield',
                            itemId: 'displaypreview',
                            fieldLabel: 'Label',
                            hideLabel: true
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});