/*
 * File: app/view/MailGrid.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('EmailPrototype.view.MailGrid', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.mailgrid',

    requires: [
        'EmailPrototype.view.MainGridToolbar',
        'Ext.toolbar.Toolbar',
        'Ext.grid.column.Template',
        'Ext.XTemplate',
        'Ext.grid.View',
        'Ext.selection.CheckboxModel'
    ],

    title: 'Mail Detail',
    columnLines: false,
    hideHeaders: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'maingridtoolbar',
                    dock: 'top'
                }
            ],
            columns: [
                {
                    xtype: 'templatecolumn',
                    tpl: [
                        '<tpl>',
                        '    <div style="white-space:normal;word-wrap:break-word;"><strong style="color:#000;">From:</strong>{from} &nbsp; &nbsp; <strong style="color:#000;">Received: </strong>{received}</div>',
                        '<div style="white-space:normal;word-wrap:break-word;"><strong style="color:#000;">Subject:</strong> {subject}</div>',
                        '    <div style="white-space:normal;word-wrap:break-word;"><i>{message}</i></div>',
                        '</tpl>'
                    ],
                    text: 'MyTemplateColumn',
                    flex: 1
                }
            ],
            selModel: Ext.create('Ext.selection.CheckboxModel', {

            })
        });

        me.callParent(arguments);
    }

});