/*
 * File: app/view/MainGridToolbar.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('EmailPrototype.view.MainGridToolbar', {
    extend: 'Ext.toolbar.Toolbar',
    alias: 'widget.maingridtoolbar',

    requires: [
        'Ext.button.Button',
        'Ext.toolbar.Spacer'
    ],

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'button',
                    itemId: 'NewButton',
                    icon: 'images/new_firstdoc_16x16.gif'
                },
                {
                    xtype: 'button',
                    icon: 'images/import_firstdoc_16x16.gif'
                },
                {
                    xtype: 'button',
                    icon: 'images/information_node.gif'
                },
                {
                    xtype: 'tbspacer',
                    flex: 1
                },
                {
                    xtype: 'button',
                    icon: 'images/sort.png',
                    text: 'Sorting'
                }
            ]
        });

        me.callParent(arguments);
    }

});